spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt?useSSL=false
    username: root
    password: Ceras@0410
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

api:
  app:
    jwtSecretKey: CerasKey
    jwtExpirationMs: 86400000